name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: docker
    steps:
      - name: Debug
        run: |
          echo "Workflow started"
          echo "Ref: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          pwd
          ls -la
